### ISSUE TITLE
Can't be installed in self-hosted ?

### ISSUE THREAD

**Issue by rmdes** [muench-dev/n8n-nodes-bluesky#10]
Hi there, I'm trying to install it like I would install any other node from the community on my (cloudron.io) self hosted N8N and the logs say : npm package not found

`Dec 07 12:33:04 <30>1 2024-12-07T11:33:04Z - ResponseError: Error loading package "n8n-nodes-bluesky" :npm package not found`

I used `n8n-nodes-bluesky` like I would do for any other nodes

Any idea what could be the cause ?

**Comment by cmuench** [comment]
@rmdes Community nodes can only run in self-hosted environments. I use it in my n8n. Sadly I cannot reproduce the issue. Is your n8n instance up-to-date?

That's how it looks in my instance.
![image](https://github.com/user-attachments/assets/91f63258-0f2e-489b-a55d-b62480de05fb)

**Comment by rmdes** [comment]
Yes I have the same screen for any other modules, my N8N is self-hosted too, just using cloudron.io stack but it's definitely self hosted.

I might ask cloudron to integrate your module directly in their Docker image, at build time.

**Comment by rmdes** [comment]
Oh wow, I tried again and voila : 
![image](https://github.com/user-attachments/assets/0d235240-7893-4e46-a8b7-622e72986182)

I have N8N version 1.70.2

**Comment by rmdes** [comment]
the complete log of the error trace is 

`Dec 09 14:13:35 - 2024-12-09T13:13:35.842Z | error | Error loading node "Bluesky" from: "/app/data/user/.n8n/nodes/node_modules/@muench-dev/n8n-nodes-bluesky/dist/nodes/Bluesky/Bluesky.node.js" - Class extends value undefined is not a constructor or null {"file":"LoggerProxy.js","function":"exports.error"}
Dec 09 14:13:37 - 2024-12-09T13:13:37.691Z | error | Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - Cause: Class extends value undefined is not a constructor or null
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - ResponseError: Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - Cause: Class extends value undefined is not a constructor or null
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at CommunityPackagesController.installPackage (/app/code/node_modules/n8n/src/controllers/community-packages.controller.ts:111:10)
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at handler (/app/code/node_modules/n8n/src/decorators/controller.registry.ts:105:12)
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at /app/code/node_modules/n8n/src/response-helper.ts:162:17
Dec 09 14:13:37 <30>1 2024-12-09T13:13:37Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - {"file":"LoggerProxy.js","function":"exports.error"}`

I'll check with the cloudron people if it's in any way related to the cloudron packaging of N8N

**Comment by cmuench** [comment]
@rmdes this was helpful.
Could be that the peerDependency to "n8n-core" causes the issue.

![image](https://github.com/user-attachments/assets/e7cf8122-b76d-41a2-a4ef-db5580c1f95b)

I will try to remove it.

**Comment by cmuench** [comment]
@rmdes freshly released v2.7.2.

**Comment by rmdes** [comment]
It's really strange, because using two different cloudron's, same N8N version, I managed to install one without issues and the other is doing this error in the UI : 

`Error installing new package
Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded Cause: Class extends value undefined is not a constructor or null`

and the same error in the logs of the container : 
`5 - 2024-12-11T23:42:55.248Z | error | Error loading node "Bluesky" from: "/app/data/user/.n8n/nodes/node_modules/@muench-dev/n8n-nodes-bluesky/dist/nodes/Bluesky/Bluesky.node.js" - Class extends value undefined is not a constructor or null {"file":"LoggerProxy.js","function":"exports.error"}
Dec 12 00:42:56 - 2024-12-11T23:42:56.938Z | error | Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - Cause: Class extends value undefined is not a constructor or null
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - ResponseError: Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - Cause: Class extends value undefined is not a constructor or null
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at CommunityPackagesController.installPackage (/app/code/node_modules/n8n/src/controllers/community-packages.controller.ts:111:10)
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at processTicksAndRejections (node:internal/process/task_queues:95:5)
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at handler (/app/code/node_modules/n8n/src/decorators/controller.registry.ts:105:12)
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - at /app/code/node_modules/n8n/src/response-helper.ts:162:17
Dec 12 00:42:56 <30>1 2024-12-11T23:42:56Z hostname f0f910e7-b3c3-44d8-90fe-14cff2105665 1361 f0f910e7-b3c3-44d8-90fe-14cff2105665 - {"file":"LoggerProxy.js","function":"exports.error"}`

**Comment by rmdes** [comment]
Trying again now :) thanks for looking into it !

**Comment by rmdes** [comment]
It keeps being inconsistent, it works in some case and same stack, same version of N8N and I can't get it to install , same error...it's really strange...will see on the cloudron.io forum what they think

**Comment by cmuench** [comment]
> It keeps being inconsistent, it works in some case and same stack, same version of N8N and I can't get it to install , same error...it's really strange...will see on the cloudron.io forum what they think

Sounds really strange. Hope they can find anything.

**Comment by rmdes** [comment]
I found that by removing a few un-used community nodes I managed to install where I couldn't before
the thing is I didn't noted which one and a removed a few at once, so now I don't really know what interfered, and the logs where not showing any issue with the pre-existence of other modules...but hell yeah, it's installed now :)

one question: is there a plan to be able to delete posts, not just reposts ? 
I want to be able to list Post ID's and then use the CID as input for deletion
but for this we should be able to use an expression in the input to delete
so then mapping could work to dynamically delete posts based on keyworks or URLs domain
![image](https://github.com/user-attachments/assets/ae0571f3-14a8-4094-b112-113e3c21d63e)

**Comment by cmuench** [comment]
I close the issue here as.

**Comment by nono2357** [comment]
Still having the issue using self-hosted latest stable n8n v1.79.3, and `Settings/Install community nodes`, popup says:
<pre>Error installing new package
Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded Cause: Class could not be found. Please check if the class is named correctly.</pre>

Log file extract:
```
Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
ResponseError: Error loading package "@muench-dev/n8n-nodes-bluesky" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
    at CommunityPackagesController.installPackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:81:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
```

**Comment by cmuench** [comment]
@nono2357 I just have synced the dependencies with the n8n-node-starter package. The "n8n-workflow" dependency was there removed from the dev dependencies.
It's just released the small change as v2.8.3.

On my local machine I tested the node in 1.79.3 via (`npx n8n start`).
I also run a docker based installation (currently with 1.79.4).

Hope the error is fixed on your machine.

**Comment by nono2357** [comment]
@cmuench Thank you, the error message is still the same after trying to install v2.8.3...

It doesn't work in my production environment even if I unistall all other community modules. However it works on an empty n8n with the same version.

**Comment by cmuench** [comment]
> [@cmuench](https://github.com/cmuench) Thank you, the error message is still the same after trying to install v2.8.3...
> 
> It doesn't work in my production environment even if I uninstall all other community modules. However it works on an empty n8n with the same version. I finally migrated all my workflows&credentials to that new n8n install and the module now works... No idea why.

Thanks for the feedback. Hopefully we will find the cause for issue someday.

**Comment by ixeres** [comment]
Can confirm the same error on my self-hosted local deployment, going to take a look internally:

<img width="1146" alt="Image" src="https://github.com/user-attachments/assets/5defb9d2-53cb-4e0d-9dcf-abf46350bc55" />
