### ISSUE TITLE
Error: This file is too large

### ISSUE THREAD

**Issue by yoavniran** [muench-dev/n8n-nodes-bluesky#112]
Hey @cmuench 

saw this was reported already in -  https://github.com/muench-dev/n8n-nodes-bluesky/issues/76

I also started seeing this just in the last few days. the full error: 

Error: This file is too large. It is 1.64MB but the maximum size is 976.56KB. at AtpAgent.call (/home/node/.n8n/nodes/node_modules/@atproto/xrpc/src/xrpc-client.ts:105:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at AppBskyFeedPostRecord.create (/home/node/.n8n/nodes/node_modules/@atproto/api/src/client/index.ts:2356:17) at postOperation (/home/node/.n8n/nodes/node_modules/@muench-dev/n8n-nodes-bluesky/nodes/Bluesky/V2/postOperations.ts:249:53) at ExecuteContext.execute (/home/node/.n8n/nodes/node_modules/@muench-dev/n8n-nodes-bluesky/nodes/Bluesky/V2/BlueskyV2.node.ts:109:23) at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:1185:9) at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:1534:27 at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:2098:11

I suppose it refers to the card image, right?

**Comment by cmuench** [comment]
@yoavniran right. If the image is too big, Bluesky is not accepting it. We need to resite the image.

It's relates to #9

**Comment by cmuench** [comment]
@yoavniran 
I released v2.11.0 with a resize function.
The resize function will resize the image to max 1.000 pixel width. Hope this will fix your issue.

**Comment by cmuench** [comment]
ok, build failed. I will fix it.

**Comment by yoavniran** [comment]
amazing! thanks for the quick turnaround
will upgrade now

**Comment by yoavniran** [comment]
hey. despite having upgraded to 2.11.0, I'm still getting the "too large" error:

![Image](https://github.com/user-attachments/assets/a6c9998f-13e9-40ee-a802-48e4fb0d7fac)

![Image](https://github.com/user-attachments/assets/8f4253e9-4c0e-491e-9b9f-f335dacfe5da)

![Image](https://github.com/user-attachments/assets/b851ce4e-a408-4ffa-873d-5a84a3edb39c)


And after seeing this with a different error (not being able to fetch the image) as well as this error, the execution doesnt continue on the error branch as it should either. The flow simply hangs on the error :(
